global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "app1_metrics"
    scrape_interval: 5s
    static_configs:
      - targets:
        - app1:81

  - job_name: "app2_metrics"
    scrape_interval: 5s
    static_configs:
      - targets:
        - app2:82